### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by samabsalom** [Phileep/mqtt_oled_display#1]
this looks great! any chance you could help me out with how to add my mqtt username and password to the sketch please?
Sam

**Comment by Phileep** [comment]
As you point out, the mqtt login for this sketch does not use a username and password.

To do this simply, amend line 153 from
`if (client.connect(client_name, willTopic, 0, willRetain, willMessage)) {`

to:
`if (client.connect(client_name, #yourmqttusername#, #yourmqttuserpassword#, willTopic, 0, willRetain, willMessage)) {`

which uses the login form of the mqtt pubsub library. documentation [here](https://pubsubclient.knolleary.net/api.html#connect4)

This suggestion is not using variables - you could do that also - it assumes you replace the 2 items highlighted by # with your actual text values (in quotes).

Let me know if it works - I don't use passwords in my setup as it is all local

Regards

Phil

**Comment by therains** [comment]
Nice work @Phileep  i am pushing mqtt states to an oled with your code via HASS.

I used your code with external mqtt by adding the below to the code

  const char *mqtt_user     = "";
 const char* mqtt_password = "";

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection as ...");
    Serial.print(client_name);
    Serial.print("..");
    // Attempt to connect
    if (client.connect(client_name, mqtt_user, mqtt_password, willTopic, 0, willRetain, willMessage)) {
      Serial.println("connected");
      // Once connected, update status to online - will Message will drop in if we go offline ...
      client.publish(willTopic,"online",true); 

This worked fine :)
